apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: j23zebia
spec:
  clusterIP: None
  ports:
  - name: redis-svc-port
    port: 6379
    targetPort: 6379
    protocol: TCP
